name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # macos-latest is assumed to behave the same as ubuntu-latest
        node-version: [12.x, 14.x, 16.x]
        package-manager: [npm, yarn, pnpm]

    env:
      PACKAGE_MANAGER: ${{ matrix.package-manager }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        if: matrix.package-manager == 'pnpm'
        with:
          version: "latest"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: ${{ matrix.package-manager }} install
      - run: node test.js
